export const siteConfig = {
  name: "Saqib Khan",
  title: "Software Engineering Student",
  description: "Software Engineering student at McMaster University with a passion for full-stack development, machine learning, and building impactful solutions. Currently seeking opportunities to apply my skills in real-world applications.",
  location: "Hamilton, ON",
  email: "khans416@mcmaster.ca",
  phone: "(+1)289-783-1055",
  resume: "/Saqib-Khan Resume 2026.pdf",
  profileImage: "/profile.jpg", 
  social: {
    github: "https://github.com/saqib-21",
    linkedin: "https://www.linkedin.com/in/saqib-khan-aa127b275/",
  },
  about: {
    bio: "I'm a Software Engineering student at McMaster University with a 3.7 GPA, expected to graduate in April 2027. I'm passionate about building full-stack applications, machine learning solutions, and robotics systems that solve real-world problems. With a focus on clean code and scalable architecture, I create impactful solutions across diverse domains.",
    highlights: [
      "Dean's Honour List recipient (2024) and Engineering Award of Excellence (2023)",
      "Led workshops teaching programming fundamentals to 50+ students",
      "Created community tools used by 1000+ local residents",
    ],
  },
  education: {
    university: "McMaster University",
    degree: "Bachelor of Software Engineering",
    gpa: "3.7 GPA",
    expectedGraduation: "April 2027",
    relevantCourses: [
      "Application of Machine Learning",
      "Software Development",
      "Data Structures and Algorithms",
      "Discrete Math",
      "Software Architecture",
      "Object-Oriented Programming",
    ],
  },
  skills: [
    "Java",
    "C",
    "C++",
    "Python",
    "JavaScript",
    "TypeScript",
    "React",
    "Next.js",
    "Node.js",
    "Express",
    "Flask",
    "Tailwind CSS",
    "HTML5",
    "CSS3",
    "MySQL",
    "PyTorch",
    "TensorFlow",
    "OpenCV",
    "MediaPipe",
    "GitHub",
    "Linux",
    "MATLAB",
    "Bash",
    "Maven",
  ],
  projects: [
    {
      title: "NeuroVision - Brain Tumor Classifier",
      description: "Full-stack medical imaging app that classifies brain tumors from MRI scans using a custom PyTorch CNN, achieving 93-100% accuracy per class on 22,000+ scans. Engineered deep learning model with 4 convolutional blocks, batch normalization, and dropout regularization.",
      image: "/projects/neurovision.png",
      tech: ["Python", "PyTorch", "Next.js", "TypeScript", "Tailwind CSS"],
      link: "https://github.com/saqib-21/NeuroVision_mri-tumour-cnn",
      featured: true,
      period: "December 2025",
    },
    {
      title: "Live Bridge Status Visualizer",
      description: "Full-stack web app with Node.js/Express backend that scrapes official bridge data and exposes it via REST API. Designed responsive Google Maps frontend with real-time geolocation and color-coded bridge markers. Used by 1000+ local residents to avoid delays from raised bridges.",
      image: "/projects/bridge-status.png",
      tech: ["React", "Node.js", "Express", "Cheerio", "Google Maps API", "Tailwind CSS"],
      link: "https://github.com/saqib-21/WellandCanalStatus",
      featured: true,
      period: "July 2025",
    },
    {
      title: "LiftEZ – Workout Tracker",
      description: "Workout tracking app using OpenCV & MediaPipe for real-time form correction and rep counting. Built Flask web app for workout logging and progress tracking. Implemented angle detection algorithms to analyze joint positions achieving >95% accuracy.",
      image: "/projects/liftez.png",
      tech: ["Python", "Flask", "OpenCV", "MediaPipe", "HTML", "CSS"],
      link: "https://github.com/saqib-21",
      featured: true,
      period: "January 2025",
    },
    {
      title: "Autonomous Rescue Drone",
      description: "Java-based state machine navigation system that enabled drones to autonomously locate stranded individuals and identify safe landing zones with 100% success in disaster terrain simulations. Applied OOP design principles and JUnit testing.",
      image: "/projects/rescue-drone.png",
      tech: ["Java", "JUnit", "OOP Design Principles"],
      link: "https://github.com/saqib-21/2AA4-Assignment2",
      featured: true,
      period: "April 2025",
    },
    {
      title: "Forever.com – Personalized Anniversary Website",
      description: "Built a responsive anniversary website with an interactive photo album, countdown timer, and personalized messaging system using Vue.js and JavaScript. Created a memorable and engaging experience for celebrating special moments.",
      image: "/projects/forever-com.png",
      tech: ["HTML", "CSS", "JavaScript", "Vue.js"],
      link: "https://github.com/saqib-21/11-03-2022",
      featured: true,
      period: "March 2025",
    },
    {
      title: "FileOps (File Organization)",
      description: "Command-line utility for file deletion, encryption, organization, and automated backups. Designed and implemented OpenSSL encryption for secure file handling with batch processing for multiple files. Collaborated with team via Git for version control, conducted code reviews, and managed conflict resolution.",
      image: "/projects/fileops.png",
      tech: ["Bash", "Linux", "GitHub", "OpenSSL"],
      link: "https://github.com/saqib-21/FileOps",
      featured: true,
      period: "November 2024",
    },
  ],
  experience: [
    {
      company: "Sumobot",
      role: "Software Engineer",
      period: "August 2025 - Present",
      description: "Led a 50+ student workshop on programming fundamentals, teaching core C++ and robotics applications. Engineered autonomous robot control software in C++, enabling adaptive, real-time responses to opponents using multi-sensor input. Integrated Arduino, Ultrasonic, and Infrared sensors. Coordinated a sub-team of 4+ programmers, overseeing project timelines and providing technical support during competitions.",
    },
    {
      company: "Event Services",
      role: "Server",
      period: "May 2022 - August 2023",
      description: "Provided attentive service at weddings and ceremonies for over 200+ guests, demonstrating strong communication skills and attention to detail.",
    },
  ],
  awards: [
    "McMaster Dean's Honour List (2024)",
    "McMaster Engineering Award of Excellence (2023)",
    "Schulich Nominee (2023)",
    "Ontario High-School Scholar (2023)",
    "High-School Council Award (2023)",
  ],
};
