export const siteConfig = {
  name: "Saqib Khan",
  title: "Software Engineering Student",
  description: "Software Engineering student at McMaster University with a passion for full-stack development, machine learning, and building impactful solutions. Currently seeking opportunities to apply my skills in real-world applications.",
  location: "Hamilton, ON",
  email: "khans416@mcmaster.ca",
  phone: "(+1)289-783-1055",
  resume: "/Saqib-Khan Resume 2026.pdf",
  profileImage: "/profile.jpg", // Optional: Add your profile picture to /public/profile.jpg (or leave as undefined to use placeholder)
  social: {
    github: "https://github.com/saqib-21",
    linkedin: "https://linkedin.com/in/saqib-khan",
  },
  about: {
    bio: "I'm a Software Engineering student at McMaster University with a 3.7 GPA, expected to graduate in April 2027. I'm passionate about building full-stack applications, machine learning solutions, and robotics systems that solve real-world problems. With a focus on clean code and scalable architecture, I create impactful solutions across diverse domains.",
    highlights: [
      "Dean's Honour List recipient (2024) and Engineering Award of Excellence (2023)",
      "Led workshops teaching programming fundamentals to 50+ students",
      "Created community tools used by 1000+ local residents",
    ],
  },
  education: {
    university: "McMaster University",
    degree: "Bachelor of Software Engineering",
    gpa: "3.7 GPA",
    expectedGraduation: "April 2027",
    relevantCourses: [
      "Application of Machine Learning",
      "Software Development",
      "Data Structures and Algorithms",
      "Discrete Math",
      "Software Architecture",
      "Object-Oriented Programming",
    ],
  },
  skills: [
    "Java",
    "C",
    "C++",
    "Python",
    "JavaScript",
    "TypeScript",
    "React",
    "Next.js",
    "Node.js",
    "Express",
    "Flask",
    "Tailwind CSS",
    "HTML5",
    "CSS3",
    "MySQL",
    "PyTorch",
    "TensorFlow",
    "OpenCV",
    "MediaPipe",
    "GitHub",
    "Linux",
    "MATLAB",
    "Bash",
    "Maven",
  ],
  projects: [
    {
      title: "NeuroVision - Brain Tumor Classifier",
      description: "Full-stack medical imaging app that classifies brain tumors from MRI scans using a custom PyTorch CNN, achieving 93-100% accuracy per class on 22,000+ scans. Engineered deep learning model with 4 convolutional blocks, batch normalization, and dropout regularization.",
      image: "/projects/neurovision.png",
      tech: ["Python", "PyTorch", "Next.js", "TypeScript", "Tailwind CSS"],
      link: "https://github.com/saqib-21",
      featured: true,
      period: "December 2025",
    },
    {
      title: "Live Bridge Status Visualizer",
      description: "Full-stack web app with Node.js/Express backend that scrapes official bridge data and exposes it via REST API. Designed responsive Google Maps frontend with real-time geolocation and color-coded bridge markers. Used by 1000+ local residents to avoid delays from raised bridges.",
      image: "/projects/bridge-status.png",
      tech: ["React", "Node.js", "Express", "Cheerio", "Google Maps API", "Tailwind CSS"],
      link: "https://github.com/saqib-21",
      featured: true,
      period: "July 2025",
    },
    {
      title: "LiftEZ – Workout Tracker",
      description: "Workout tracking app using OpenCV & MediaPipe for real-time form correction and rep counting. Built Flask web app for workout logging and progress tracking. Implemented angle detection algorithms to analyze joint positions achieving >95% accuracy.",
      image: "/projects/liftez.png",
      tech: ["Python", "Flask", "OpenCV", "MediaPipe", "HTML", "CSS"],
      link: "https://github.com/saqib-21",
      featured: true,
      period: "January 2025",
    },
    {
      title: "Autonomous Rescue Drone",
      description: "Java-based state machine navigation system that enabled drones to autonomously locate stranded individuals and identify safe landing zones with 100% success in disaster terrain simulations. Applied OOP design principles and JUnit testing.",
      image: "/projects/rescue-drone.png",
      tech: ["Java", "JUnit", "OOP Design Principles"],
      link: "https://github.com/saqib-21",
      featured: false,
      period: "April 2025",
    },
  ],
  experience: [
    {
      company: "Sumobot",
      role: "Software Engineer",
      period: "August 2025 - Present",
      description: "Led a 50+ student workshop on programming fundamentals, teaching core C++ and robotics applications. Engineered autonomous robot control software in C++, enabling adaptive, real-time responses to opponents using multi-sensor input. Integrated Arduino, Ultrasonic, and Infrared sensors. Coordinated a sub-team of 4+ programmers, overseeing project timelines and providing technical support during competitions.",
    },
    {
      company: "Event Services",
      role: "Server",
      period: "May 2022 - August 2023",
      description: "Provided attentive service at weddings and ceremonies for over 200+ guests, demonstrating strong communication skills and attention to detail.",
    },
  ],
  awards: [
    "McMaster Dean's Honour List (2024)",
    "McMaster Engineering Award of Excellence (2023)",
    "Schulich Nominee (2023)",
    "Ontario High-School Scholar (2023)",
    "High-School Council Award (2023)",
  ],
};
